### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by RonKen-coder** [RonKen-coder/prework-study-guide#1]
#HTML

## User Story
As a bootcamp student
I want the prework notes to be structured on a webpage
so that I can easily find and read information

## Acceptance Criteria
GIVEN a Prework Study Guide website
When I visit the website in my browser
Then I see four boxes titled HTML, CSS, GIT and JavaScript with associated notes listed

**Comment by DevLeoCunha** [comment]
You can create an HTML file with VSCODE. Insert simple tags and relative content. You can download an extension in VSCODE so you can check the HTML document in real time to see how the created notes are doing. I hope I helped.
